name: Build Container

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:

    - uses: actions/checkout@v1

    - name: Build the image
      run: docker build . --file Dockerfile --tag rust-esp:${{ github.sha }}

    - name: Authenticate
      run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login quay.io --username ${{secrets.REGISTRY_USERNAME}} --password-stdin

    - name: Tag the image (master)
      if: github.ref == 'refs/heads/master'
      run: docker tag rust-esp:${{ github.sha }} quay.io/ctron/rust-esp:latest
    - name: Push the image (master)
      if: github.ref == 'refs/heads/master'
      run: docker push quay.io/ctron/rust-esp:latest

    - name: Tag the image (develop)
      if: github.ref == 'refs/heads/develop'
      run: docker tag rust-esp:${{ github.sha }} quay.io/ctron/rust-esp:develop
    - name: Push the image (develop)
      if: github.ref == 'refs/heads/develop'
      run: docker push quay.io/ctron/rust-esp:develop
